name: "Setup Node"
description: "Setup Node"
inputs:
  node-version:
    description: "Node version if Node required"
    default: "10.15.3"
    required: false
runs:
  using: "composite"
  steps:
    - name: Cache node modules
      if: ${{ inputs.depends-on-node }}
      uses: actions/cache@v2
      with:
        submodules: true
        # npm cache files are stored in `~/.npm` on ubuntu-latest
        path: ~/.npm
        key: ${{ runner.os }}-build-cache-node-modules
        restore-keys: |
          ${{ runner.os }}-build-cache-node-modules

      # Setup Node
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}

    # Install Node dependencies
    - name: Install Dependencies
      run: |
        echo //npm.pkg.github.com/:_authToken=${{ secrets.github-pat }} >> ~/.npmrc
        npm ci
      shell: bash
