name: "JavaGradleBuild"

on:
  workflow_call:
    inputs:
      java-version:
        description: "Java Version"
        type: string
        required: true
      gradle-version:
        description: "Gradle Version"
        type: string
        required: true
      os-version:
        description: "OS Version"
        type: string
        default: ubuntu-latest
        required: false
      depends-on-node:
        description: "Is Node required for build?"
        type: boolean
        default: false
        required: false
      node-version:
        description: "Node version if Node required"
        type: string
        default: "10.15.3"
        required: false
    secrets:
      github-username:
        description: "GitHub Username"
        required: true
      github-pat:
        description: "GitHub Packages Token"
        required: true

jobs:
  build:
    runs-on: ${{ inputs.os-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ inputs.java-version }}

      - name: Cache node modules
        if: ${{ inputs.depends-on-node }}
        uses: actions/cache@v2
        with:
          submodules: true
          # npm cache files are stored in `~/.npm` on ubuntu-latest
          path: ~/.npm
          key: ${{ runner.os }}-build-cache-node-modules
          restore-keys: |
            ${{ runner.os }}-build-cache-node-modules

        # Setup Node
      - name: Setup node
        if: ${{ inputs.depends-on-node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ inputs.node-version }}

      # Install Node dependencies
      - name: Install Dependencies
        if: ${{ inputs.depends-on-node }}
        run: |
          echo //npm.pkg.github.com/:_authToken=${{ secrets.github-pat }} >> ~/.npmrc
          npm ci

      #Build Gradle
      - name: Build Gradle
        env:
          GITHUB_USERNAME: ${{ secrets.github-username }}
          GITHUB_TOKEN: ${{ secrets.github-pat }}
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: ${{ inputs.gradle-version }}
          arguments: build -x test
          
      #Running Test
      - name: Running  Gradle Test
        env:
          GITHUB_USERNAME: ${{ secrets.github-username }}
          GITHUB_TOKEN: ${{ secrets.github-pat }}
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: ${{ inputs.gradle-version }}
          arguments: test